spring: 
  datasource: 
    url: jdbc:mariadb://localhost:3306/Sales
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa: 
    hibernate:
      ddl-auto: validate

