/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProductController;
import Model.Payment;
import java.awt.Color;
import Model.Product;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author luis
 */
public class AddSale extends javax.swing.JFrame {
    ProductController productController = new ProductController();
    /**
     * Creates new form AddSale
     */
    public AddSale() throws SQLException, ClassNotFoundException {
        initComponents();
        CBProInsert(productController.getAllProducts());
    }
    public void CBProInsert(ArrayList<Product> list) {
        for (Product product : list) {
            CBProduct.addItem(product.getName());
        }
    }
    public void CBPayInsert(ArrayList<Payment> list) {
        for (Payment payment : list) {
            CBPayment.addItem("");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CBPayment = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CBProduct = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PanelBtnAdd = new javax.swing.JPanel();
        BtnAdd = new javax.swing.JPanel();
        AddLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBPayment.setBackground(new java.awt.Color(255, 255, 255));
        CBPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBPayment.setBorder(null);
        jPanel1.add(CBPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 360, 50));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Shipping Address");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 360, 50));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Payment Method");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        CBProduct.setBackground(new java.awt.Color(255, 255, 255));
        CBProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...." }));
        CBProduct.setBorder(null);
        jPanel1.add(CBProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 360, 50));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Product");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SALE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 380));

        PanelBtnAdd.setBackground(new java.awt.Color(255, 255, 255));
        PanelBtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        PanelBtnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBtnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBtnAddMouseExited(evt);
            }
        });
        PanelBtnAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAdd.setBackground(new java.awt.Color(255, 255, 255));

        AddLabel.setBackground(new java.awt.Color(255, 255, 255));
        AddLabel.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        AddLabel.setForeground(new java.awt.Color(0, 0, 0));
        AddLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddLabel.setText("ADD SALE");
        AddLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnAddLayout = new javax.swing.GroupLayout(BtnAdd);
        BtnAdd.setLayout(BtnAddLayout);
        BtnAddLayout.setHorizontalGroup(
            BtnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnAddLayout.createSequentialGroup()
                .addComponent(AddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BtnAddLayout.setVerticalGroup(
            BtnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnAddLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelBtnAdd.add(BtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 270, 50));

        getContentPane().add(PanelBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 400, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void PanelBtnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnAddMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_PanelBtnAddMouseEntered

    private void PanelBtnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnAddMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_PanelBtnAddMouseExited

    private void AddLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLabelMouseEntered
        // TODO add your handling code here:
        BtnAdd.setBackground(new Color(255,255,51));
        AddLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_AddLabelMouseEntered

    private void AddLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLabelMouseExited
        // TODO add your handling code here:
        BtnAdd.setBackground(new Color(255,255,255));
        AddLabel.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_AddLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddSale().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddSale.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddSale.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLabel;
    private javax.swing.JPanel BtnAdd;
    private javax.swing.JComboBox<String> CBPayment;
    private javax.swing.JComboBox<String> CBProduct;
    private javax.swing.JPanel PanelBtnAdd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
